FROM node:7-alpine
MAINTAINER Xeltor

LABEL h265ize_version="bleading edge" architecture="amd64"

RUN apk add --no-cache --update-cache git ffmpeg && \
    npm install Xeltor/h265ize --global --no-optional && \
    apk del git && \
    mkdir /watch && \
    rm /var/cache/apk/* && \
	groupadd -g 100 users && \
	useradd -u 99 -g users nobody && \
	chown -R 99:100 /h265ize

VOLUME ["/watch"]
WORKDIR /h265ize

ENTRYPOINT ["/usr/local/bin/h265ize", "--watch", "/watch"]
