FROM node:7-alpine
MAINTAINER Xeltor

LABEL h265ize_version="bleading edge" architecture="amd64"

RUN apk add --no-cache --update-cache git ffmpeg && \
    npm install Xeltor/h265ize --global --no-optional && \
    apk del git && \
    mkdir /watch && mkdir /encode && \
    rm /var/cache/apk/*

VOLUME ["/watch", "/encode"]
WORKDIR /h265ize

ENTRYPOINT ["/usr/local/bin/h265ize", "-d", "/encode", "--delete", "--watch", "/watch"]