FROM node:7-alpine
MAINTAINER Xeltor

LABEL h265ize_version="bleading edge" architecture="amd64"

RUN apk add --no-cache --update-cache git ffmpeg && \
    npm install FallingSnow/h265ize --global --no-optional && \
    apk del git && \
    mkdir /input && \
	mkdir /h265ize && \
	mkdir /h265ize/h265 && \
	chown -R 99:100 /h265ize && \
    rm /var/cache/apk/*

VOLUME ["/input"]
WORKDIR /h265ize

ENTRYPOINT ["/usr/local/bin/h265ize", "--watch", "/input"]